### ISSUE TITLE
How to test the model?

### ISSUE THREAD

**Issue by tushar-semwal** [ateniolatobi/Secure-Federated-Learning-Project#1]
Hi which model should I use for test dataset? I tried central_model but it does not work. Also, does this code do encryption of weights? Help appreciated.

**Comment by tushar-semwal** [comment]
I solved the problem. Please ignore.

**Comment by ateniolatobi** [comment]
Hello @tushar-semwal , I apologize my reply is coming a bit late, I have not been frequent on GitHub Lately. I am very happy you were able to solve the issue.

Cheers.
